eureka:
  client:
    #    获取微服务
    fetch-registry: true
    #    微服务的消费者，因此不需要将自己注册进微服务
#    register-with-eureka: true
    #    注册中心地址
    service-url:
      defaultZone: http://localhost:7001/eureka
  #要访问http://${eureka.instance.hostname}:${server.port}，坑爹
  instance:
    #    微服务的实例id
    instance-id: consumer80


server:
  port: 80


#全局配置
# 请求连接的超时时间 默认的时间为 1 秒
#ribbon:
#  ConnectTimeout: 5000
#  # 请求处理的超时时间
#  ReadTimeout: 5000
logging:
  level:
    com.byy.service.ConsumerDeptService: debug
feign:
  hystrix:
    enabled: true